chats-settings:
    administrators:
        - 1039061325    # pavel
        - 161855902     # max
        - 1004758635    # alex
    anniversary-numbers-delta: 3
    anniversary-numbers:
        - 5
        - 50
        - 100
        - 500
        - 777
        - 1000
        - 5000
        - 10000
    chats-settings:
        -1001523814996: #Хакатон и телеграм бот (Skillbox)
            - -1001523814996 # Хакатон и телеграм бот (Skillbox)
            - -1001781082670 # Java-диплом с нуля (Skillbox)

    rewrite-chats-settings-in-database-on-startup: false

message-templates:
    variables:
        chat-name: "{НазваниеГруппы}"
        user-name: "{ИмяУчастника}"
        user-nickname: "{НикУчастника}"
        join-date: "{ВремяВступления}"
        join-number: "{НомерВступления}"
    plugs:
        no-nick: "ника нет"
        winner-crown: "👑👑👑"
        join-date-format: "dd.MM.yy HH:mm"
    join-congratulation: "🎉 Поздравляю, *{ИмяУчастника}*, как же удачно попали в нужное время и в нужное время!\nВы *{НомерВступления}* участник коммьюнити.\nВас ждут плюшки и печенюшки!🎉"
    join-alert: " 🎉 В *{НазваниеГруппы}* группу вступил юбилейный пользователь\n{ИмяУчастника} (*{НикУчастника}*),\n 🔢 *{НомерВступления}* 🕐 {ВремяВступления}"
    join-user-info: " 👤{ИмяУчастника} ({НикУчастника}),\n 🔢 *{НомерВступления}* 🕐 {ВремяВступления}"
