version: "3.9"
services:
    postgres:
        container_name: postgres
        image: postgres:alpine
        restart: always
        ports:
            - "5431:5432"
        environment:
            POSTGRES_DB: ${DATASOURCE_DB:-tg-bot-users}
            POSTGRES_USER: ${DATASOURCE_USER:-tg-admin}
            POSTGRES_PASSWORD: ${DATASOURCE_PASS:-postgres}
        volumes:
            - C:\docker\postgres:/var/lib/postgres
    tg-bot-users:
        container_name: tg-bot-users
        image: tg-bot-users
        restart: always
        build:
            context: .
        ports:
            - "8080:8080"
        environment:
            BOT_USER_NAME: ${BOT_USER_NAME}
            BOT_TOKEN: ${BOT_TOKEN}
            DATASOURCE_URL: ${DATASOURCE_URL:-jdbc:postgresql://host.docker.internal:5431/}${DATASOURCE_DB:-tg-bot-users}
            DATASOURCE_USER: ${DATASOURCE_USER:-tg-admin}
            DATASOURCE_PASS: ${DATASOURCE_PASS:-postgres}
        depends_on:
            postgres:
                condition: service_started